### ISSUE TITLE
Resetting recoveryOf during transfer

### ISSUE THREAD

**Issue by vrypan** [farcasterxyz/contracts#194] opened 2023-03-03 08:43 UTC
https://github.com/farcasterxyz/contracts/blob/0dd302ffe51a34508f1eada4de6ba6622097c457/src/IdRegistry.sol#L274

I can see two use cases for transferring fids: 

1. Transfer to new wallet (same owner)
2. Transfer to a new owner.

If the second case is expected to be the typical use case, then retting recoveryOf is a good decision, and the UI should make sure to let the new owner know that recovery is null and that they may want to set one. The possible problem in this case is owners just transferring between wallets do not set a new recovery address, even though they had one before, because they don't have it handy, or because gas price is high and they "will do it later". Also, transferring to the wrong address by mistake (ex. typo) is unrecoverable.

However, if the first case is expected to be the typical one, I think that recoveryOf should not be reset during transfer. I'm moving my FID to a new wallet, I most probably do not want to change the recovery address. The problem here is if I transfer to a totally different owner and he is not aware that I can use my recovery address to claim it back. So, in this case, the UI should make sure that I should set a new recovery address.

Both approaches have their pros and cons, but I think that we should optimise for 1 and leave `recoveryOf` unchanged.

**Comment by varunsrin** [comment] 2023-03-04 10:35
there are three reasons why people transfer: 

1. transferring to a new wallet for convenience (eg i prefer rainbow over metamask)
2. transferring to a new wallet for security (eg i am worried my seed phrase was exposed) 
3. transferring to a new owner because the account changes hands (eg i sold my company) 

If we go down the path of not resetting recovery, it means that a malicious party (an attacker in case 2, seller in case 3) can perform the transfer and then make an on-chain request to transfer the fid back which the other party might not notice or respond to in time. 

I agree that it does make the case for (1) better where you enter the wrong wallet address. The thing is that (1) is a well known problem for all crypto transfers that users and applications are aware of and working to fix. while the attack vector is much more subtle and likely to be unexpected behavior. 

There's another reason to reset it - to keep it aligned with the behavior of the NameRegistry so that users don't have to think about two different recovery properties when using Farcaster. In the case of the NameRegistry resetting the recovery is much more important because it is an ERC-721 and might cause lots of unexpected behaviors in auctions and other systems that do not assume a recovery mechanism.

**Closed by varunsrin** 2023-03-04 10:35 UTC
